// AUTO-GENERATED by scripts/sync-assets.js — do not edit manually.
// Edit files in storefront/ and run: npm run sync-assets

export const WISHLIST_BTN_JS = `(function () {
  // Event delegation — handles clicks on any matching button, even if duplicated in DOM
  document.addEventListener('click', function (e) {
    const wishlistBtn = e.target.closest('.wishlist-btn[data-product-id]');
    if (wishlistBtn) { handleToggle(wishlistBtn); return; }

    const shareBtn = e.target.closest('.share-btn--overlay');
    if (shareBtn) { handleShare(shareBtn); }
  });

  // Check initial wishlist state on load
  const btn = document.querySelector('.wishlist-btn[data-product-id]');
  if (btn) checkInitialState(btn.dataset.productId);

  function setActive(isActive) {
    document.querySelectorAll('.wishlist-btn[data-product-id]').forEach((b) => {
      b.classList.toggle('active', isActive);
      b.setAttribute('aria-pressed', String(isActive));
    });
  }

  function setLoading(isLoading) {
    document.querySelectorAll('.wishlist-btn[data-product-id]').forEach((b) => {
      b.classList.toggle('is-loading', isLoading);
    });
  }

  async function checkInitialState(productId) {
    try {
      const res = await fetch(\`/apps/wishlist/check?product_id=\${productId}\`);
      if (!res.ok) return;
      const data = await res.json();
      setActive(data.is_wishlisted);
    } catch {
      // silently ignore — button stays in default state
    }
  }

  async function handleToggle(btn) {
    const productId = btn.dataset.productId;
    const previousState = btn.classList.contains('active');

    // Optimistic update — flip the UI immediately, reconcile with the server after.
    setActive(!previousState);
    setLoading(true);
    try {
      const res = await fetch('/apps/wishlist/toggle', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ product_id: productId }),
      });

      if (res.status === 401) {
        setActive(previousState);
        window.location.href =
          '/account/login?return_url=' + encodeURIComponent(window.location.pathname);
        return;
      }

      if (!res.ok) throw new Error(\`Error \${res.status}\`);

      const data = await res.json();
      setActive(data.is_wishlisted);
    } catch {
      setActive(previousState);
      alert('Could not update wishlist. Please try again.');
    } finally {
      setLoading(false);
    }
  }

  async function handleShare(btn) {
    const url = window.location.href;
    try {
      await navigator.clipboard.writeText(url);
    } catch {
      const ta = document.createElement('textarea');
      ta.value = url;
      ta.style.cssText = 'position:fixed;opacity:0';
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
    }
    btn.classList.add('copied');
    setTimeout(() => btn.classList.remove('copied'), 2000);
  }
})();
`;

export const WISHLIST_PAGE_JS = `(function () {
  const root = document.getElementById('wishlist-root');
  const grid = document.getElementById('wishlist-grid');
  const emptyEl = document.getElementById('wishlist-empty');
  const emptyText = document.getElementById('wishlist-empty-text');
  const loadingEl = document.getElementById('wishlist-loading');

  const locale     = root.dataset.locale     || 'en';
  const currency   = root.dataset.currency   || 'USD';
  const localeRoot = root.dataset.localeRoot || '/';

  const i18n = {
    loginText:   root.dataset.loginText,
    errorText:   root.dataset.errorText,
    removeLabel: root.dataset.removeLabel,
  };

  function localizeUrl(path) {
    const base = localeRoot === '/' ? '' : localeRoot.replace(/\\/$/, '');
    return base + path;
  }

  function formatPrice(amount) {
    return new Intl.NumberFormat(locale, {
      style: 'currency',
      currency,
    }).format(amount);
  }

  function renderProducts(products) {
    grid.innerHTML = products
      .map(
        (p) => \`
        <div class="wishlist-card" data-product-id="\${p.id}">
          <a href="\${localizeUrl(p.url)}" class="wishlist-card__image-link">
            \${
              p.image
                ? \`<img src="\${p.image}" alt="\${p.title}" class="wishlist-card__image" loading="lazy">\`
                : \`<div class="wishlist-card__image-placeholder"></div>\`
            }
          </a>
          <div class="wishlist-card__info">
            <a href="\${localizeUrl(p.url)}" class="wishlist-card__title">\${p.title}</a>
            <p class="wishlist-card__price">\${formatPrice(p.price)}</p>
          </div>
          <button class="wishlist-card__remove" data-product-id="\${p.id}" aria-label="\${i18n.removeLabel}">
            &times;
          </button>
        </div>
      \`
      )
      .join('');

    grid.querySelectorAll('.wishlist-card__remove').forEach((btn) => {
      btn.addEventListener('click', handleRemove);
    });
  }

  async function handleRemove(e) {
    const productId = e.currentTarget.dataset.productId;
    const card = grid.querySelector(\`.wishlist-card[data-product-id="\${productId}"]\`);

    // Optimistic update — hide the card immediately, reconcile with the server after.
    card.style.display = 'none';

    try {
      const res = await fetch('/apps/wishlist/toggle', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ product_id: productId }),
      });

      if (!res.ok) throw new Error('Failed to remove');

      card.remove();

      if (grid.children.length === 0) emptyEl.style.display = 'flex';
    } catch {
      card.style.display = '';
      alert('Could not remove product. Please try again.');
    }
  }

  async function loadWishlist() {
    try {
      const res = await fetch('/apps/wishlist/list');

      if (res.status === 401) {
        loadingEl.style.display = 'none';
        emptyEl.style.display = 'flex';
        emptyText.textContent = i18n.loginText;
        return;
      }

      if (!res.ok) throw new Error(\`Error \${res.status}\`);

      const data = await res.json();
      loadingEl.style.display = 'none';

      if (!data.products || data.products.length === 0) {
        emptyEl.style.display = 'flex';
        return;
      }

      renderProducts(data.products);
    } catch (err) {
      loadingEl.style.display = 'none';
      emptyEl.style.display = 'flex';
      emptyText.textContent = i18n.errorText;
      console.error('[Wishlist]', err);
    }
  }

  loadWishlist();
})();
`;

export const WISHLIST_PAGE_LIQUID = `<style>
  .wishlist-page {
    padding-top: 4rem;
    padding-bottom: 6rem;
  }

  .wishlist-page__title {
    font-size: 2.4rem;
    font-weight: 600;
    margin-bottom: 3rem;
    border-bottom: 1px solid rgba(var(--color-foreground), 0.1);
    padding-bottom: 1.5rem;
  }

  /* Grid */
  .wishlist-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(220px, 1fr));
    gap: 2.4rem;
  }

  /* Card */
  .wishlist-card {
    position: relative;
    border: 1px solid rgba(var(--color-foreground), 0.1);
    border-radius: 0.8rem;
    overflow: hidden;
    background: rgb(var(--color-background));
    transition: box-shadow 0.2s ease;
  }

  .wishlist-card:hover {
    box-shadow: 0 4px 16px rgba(0, 0, 0, 0.1);
  }

  .wishlist-card__image-link {
    display: block;
    aspect-ratio: 1 / 1;
    overflow: hidden;
    background: rgba(var(--color-foreground), 0.04);
  }

  .wishlist-card__image {
    width: 100%;
    height: 100%;
    object-fit: cover;
    transition: transform 0.3s ease;
  }

  .wishlist-card:hover .wishlist-card__image {
    transform: scale(1.04);
  }

  .wishlist-card__image-placeholder {
    width: 100%;
    height: 100%;
    background: rgba(var(--color-foreground), 0.06);
  }

  .wishlist-card__info {
    padding: 1.2rem 1.4rem 1.4rem;
  }

  .wishlist-card__title {
    display: block;
    font-size: 1.4rem;
    font-weight: 500;
    color: rgb(var(--color-foreground));
    text-decoration: none;
    margin-bottom: 0.6rem;
    line-height: 1.4;
    overflow: hidden;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
  }

  .wishlist-card__title:hover {
    text-decoration: underline;
  }

  .wishlist-card__price {
    font-size: 1.4rem;
    font-weight: 600;
    color: rgb(var(--color-foreground));
    margin: 0;
  }

  .wishlist-card__remove {
    position: absolute;
    top: 0.8rem;
    right: 0.8rem;
    width: 2.8rem;
    height: 2.8rem;
    border-radius: 50%;
    border: none;
    background: rgb(var(--color-background));
    color: rgb(var(--color-foreground));
    font-size: 1.6rem;
    line-height: 1;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    opacity: 0;
    transition: opacity 0.2s ease, background 0.2s ease;
    box-shadow: 0 1px 4px rgba(0, 0, 0, 0.15);
  }

  .wishlist-card:hover .wishlist-card__remove {
    opacity: 1;
  }

  .wishlist-card__remove:hover {
    background: #e63946;
    color: #fff;
  }

  /* Empty state */
  .wishlist-empty {
    display: none;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 6rem 2rem;
    text-align: center;
    gap: 1.6rem;
  }

  .wishlist-empty__icon {
    color: rgba(var(--color-foreground), 0.2);
  }

  .wishlist-empty__title {
    font-size: 2rem;
    font-weight: 600;
    margin: 0;
  }

  .wishlist-empty__text {
    font-size: 1.4rem;
    color: rgba(var(--color-foreground), 0.6);
    margin: 0;
  }

  /* Loading skeleton */
  .wishlist-loading {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(220px, 1fr));
    gap: 2.4rem;
  }

  .wishlist-skeleton {
    border-radius: 0.8rem;
    overflow: hidden;
    border: 1px solid rgba(var(--color-foreground), 0.08);
  }

  .wishlist-skeleton__image {
    aspect-ratio: 1 / 1;
    background: rgba(var(--color-foreground), 0.06);
    animation: skeleton-pulse 1.4s ease-in-out infinite;
  }

  .wishlist-skeleton__info {
    padding: 1.2rem 1.4rem 1.4rem;
    display: flex;
    flex-direction: column;
    gap: 0.8rem;
  }

  .wishlist-skeleton__line {
    height: 1.2rem;
    border-radius: 0.4rem;
    background: rgba(var(--color-foreground), 0.06);
    animation: skeleton-pulse 1.4s ease-in-out infinite;
  }

  .wishlist-skeleton__line--short {
    width: 40%;
  }

  @keyframes skeleton-pulse {
    0%, 100% { opacity: 1; }
    50% { opacity: 0.4; }
  }
</style>

<div class="wishlist-page page-width"
  id="wishlist-root"
  data-locale="{{ request.locale.iso_code }}"
  data-currency="{{ cart.currency.iso_code }}"
  data-locale-root="{{ routes.root_url }}"
  data-login-text="{{ 'wishlist.login_required' | t }}"
  data-error-text="{{ 'wishlist.error' | t }}"
  data-remove-label="{{ 'wishlist.remove' | t }}"
>
  <h1 class="wishlist-page__title">{{ 'wishlist.title' | t }}</h1>
  <div class="wishlist-grid" id="wishlist-grid"></div>

  <div class="wishlist-empty" id="wishlist-empty">
    <svg class="wishlist-empty__icon" width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
      <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/>
    </svg>
    <p class="wishlist-empty__title">{{ 'wishlist.empty_title' | t }}</p>
    <p class="wishlist-empty__text" id="wishlist-empty-text">{{ 'wishlist.empty_text' | t }}</p>
    <a href="/collections/all" class="button">{{ 'wishlist.browse' | t }}</a>
  </div>

  <div class="wishlist-loading" id="wishlist-loading">
    {%- for i in (1..4) -%}
      <div class="wishlist-skeleton">
        <div class="wishlist-skeleton__image"></div>
        <div class="wishlist-skeleton__info">
          <div class="wishlist-skeleton__line"></div>
          <div class="wishlist-skeleton__line"></div>
          <div class="wishlist-skeleton__line wishlist-skeleton__line--short"></div>
        </div>
      </div>
    {%- endfor -%}
  </div>
</div>

<script src="{{ 'wishlist-page.js' | asset_url }}" defer></script>
`;

export const WISHLIST_BTN_CSS = `
/* wishlist-app:css-start */
.wishlist-btn--overlay {
  position: absolute; top: 12px; right: 12px; z-index: 2;
  width: 36px; height: 36px;
  display: flex; align-items: center; justify-content: center;
  background: rgba(255,255,255,0.9); border: none; border-radius: 50%;
  cursor: pointer; box-shadow: 0 1px 4px rgba(0,0,0,0.15);
  transition: transform 0.15s ease;
}
.wishlist-btn--overlay:hover { transform: scale(1.1); }
.wishlist-btn--overlay .icon-heart { color: #555; transition: all 0.2s ease; }
.wishlist-btn--overlay.active .icon-heart { fill: #e63946; stroke: #e63946; color: #e63946; }
.wishlist-btn--overlay.is-loading { opacity: 0.6; pointer-events: none; }

.share-btn--overlay {
  position: absolute; top: 56px; right: 12px; z-index: 2;
  width: 36px; height: 36px;
  display: flex; align-items: center; justify-content: center;
  background: rgba(255,255,255,0.9); border: none; border-radius: 50%;
  cursor: pointer; box-shadow: 0 1px 4px rgba(0,0,0,0.15);
  transition: transform 0.15s ease;
}
.share-btn--overlay:hover { transform: scale(1.1); }
.share-btn--overlay .icon-share,
.share-btn--overlay .icon-check { position: absolute; transition: opacity 0.2s ease, transform 0.2s ease; }
.share-btn--overlay .icon-share { color: #555; opacity: 1; transform: scale(1); }
.share-btn--overlay .icon-check { color: #22a861; opacity: 0; transform: scale(0.5); }
.share-btn--overlay.copied { transform: scale(1.15); }
.share-btn--overlay.copied .icon-share { opacity: 0; transform: scale(0.5); }
.share-btn--overlay.copied .icon-check { opacity: 1; transform: scale(1); }
/* wishlist-app:css-end */
`;

export const WISHLIST_BTN_HTML = `<!-- wishlist-app:btn-start -->
        <button
          type="button"
          class="wishlist-btn wishlist-btn--overlay"
          data-product-id="{{ product.id }}"
          aria-label="Add to wishlist"
          aria-pressed="false"
        >
          <svg class="icon-heart" viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/>
          </svg>
        </button>
        <button
          type="button"
          class="share-btn share-btn--overlay"
          aria-label="Copy product link"
        >
          <svg class="icon-share" viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2">
            <circle cx="18" cy="5" r="3"/>
            <circle cx="6" cy="12" r="3"/>
            <circle cx="18" cy="19" r="3"/>
            <line x1="8.59" y1="13.51" x2="15.42" y2="17.49"/>
            <line x1="15.41" y1="6.51" x2="8.59" y2="10.49"/>
          </svg>
          <svg class="icon-check" viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2.5">
            <polyline points="20 6 9 17 4 12"/>
          </svg>
        </button>
        <!-- wishlist-app:btn-end -->
`;

export const WISHLIST_PAGE_TEMPLATE_JSON = `{
  "sections": {
    "main": {
      "type": "wishlist-page",
      "settings": {}
    }
  },
  "order": ["main"]
}`;

export const WISHLIST_LOCALE_EN    = `{
  "wishlist": {
    "title": "My Wishlist",
    "empty_title": "Your wishlist is empty",
    "empty_text": "Save products you love and find them here.",
    "browse": "Browse products",
    "login_required": "Please log in to view your wishlist.",
    "error": "Something went wrong. Please refresh the page.",
    "remove": "Remove from wishlist"
  }
}`;
export const WISHLIST_LOCALE_JA    = `{
  "wishlist": {
    "title": "お気に入りリスト",
    "empty_title": "お気に入りリストは空です",
    "empty_text": "気に入った商品を保存して、後で見つけましょう。",
    "browse": "商品を見る",
    "login_required": "お気に入りリストを見るにはログインしてください。",
    "error": "エラーが発生しました。ページを更新してください。",
    "remove": "お気に入りから削除"
  }
}`;
export const WISHLIST_LOCALE_ZH_TW = `{
  "wishlist": {
    "title": "我的願望清單",
    "empty_title": "您的願望清單是空的",
    "empty_text": "儲存您喜愛的商品，在這裡找到它們。",
    "browse": "瀏覽商品",
    "login_required": "請登入以查看您的願望清單。",
    "error": "發生錯誤，請重新整理頁面。",
    "remove": "從願望清單移除"
  }
}`;
export const WISHLIST_LOCALE_KO    = `{
  "wishlist": {
    "title": "위시리스트",
    "empty_title": "위시리스트가 비어 있습니다",
    "empty_text": "마음에 드는 상품을 저장하고 여기서 찾아보세요.",
    "browse": "상품 둘러보기",
    "login_required": "위시리스트를 보려면 로그인해 주세요.",
    "error": "오류가 발생했습니다. 페이지를 새로 고침해 주세요.",
    "remove": "위시리스트에서 제거"
  }
}`;
