#!/usr/bin/env node
// Reads files from storefront/ and regenerates src/install/assets.ts.
// Run with: npm run sync-assets

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');

function read(relPath) {
  return fs.readFileSync(path.join(root, relPath), 'utf8');
}

// Escape content for embedding inside a TypeScript template literal.
function toTsLiteral(content) {
  return content
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
}

const btnJs       = read('storefront/wishlist-btn.js');
const pageJs      = read('storefront/wishlist-page.js');
const pageLiquid  = read('storefront/wishlist-page.liquid');
const btnCss      = read('storefront/wishlist-btn.css');
const btnHtml     = read('storefront/wishlist-btn.html');
const templateJson = read('storefront/page.wishlist.json');

const output = `// AUTO-GENERATED by scripts/sync-assets.js — do not edit manually.
// Edit files in storefront/ and run: npm run sync-assets

export const WISHLIST_BTN_JS = \`${toTsLiteral(btnJs)}\`;

export const WISHLIST_PAGE_JS = \`${toTsLiteral(pageJs)}\`;

export const WISHLIST_PAGE_LIQUID = \`${toTsLiteral(pageLiquid)}\`;

export const WISHLIST_BTN_CSS = \`${toTsLiteral(btnCss)}\`;

export const WISHLIST_BTN_HTML = \`${toTsLiteral(btnHtml)}\`;

export const WISHLIST_PAGE_TEMPLATE_JSON = \`${toTsLiteral(templateJson.trim())}\`;
`;

const outPath = path.join(root, 'src', 'install', 'assets.ts');
fs.writeFileSync(outPath, output);
console.log('✓ src/install/assets.ts regenerated from storefront/');
